### ISSUE TITLE
composer.locks breaks app depending on php version

### ISSUE THREAD

**Issue by Tobion** [symfony/symfony-standard#858]
Some history: We removed the lock file in https://github.com/symfony/symfony-standard/commit/58ae85a406409b86a313de22d17d706e5a8823b2 because the installation depends on the icu version. As we removed our icu library, the lock file was reintroduced in https://github.com/symfony/symfony-standard/commit/847d37cfbb868ce979bd16adc37ae5f60f467c74

But we still have a similar problem: The installation depends on the PHP version that is used.
Symfony 2.x is compatible with PHP >= 5.3.9. So we would need to make sure the installation actually works with this PHP version. But I'm sure it fails now (have not tried it) because the recent symfony release now locks in ORM 2.5 which is only compatible with PHP >= 5.4, see https://github.com/symfony/symfony-standard/blob/v2.7.4/composer.lock#L715

So people using PHP 5.3 will not be able to run our locked in release. We could work-around this by fixing the PHP version inside our composer.json that is used to update the lock file with https://getcomposer.org/doc/06-config.md#platform

But that could in theory also fail for people that use a newer PHP version. E.g. there could be a library that releases different versions for PHP 5.x and PHP 7. So if we lock in the one for 5.3.9, a user coming with PHP 7 might not be able to run symfony as well.

The only solution I see is to remove the lock file again.

**Comment by fabpot** [comment]
Seems (unfortunately) reasonable.

**Comment by stof** [comment]
We can use ``config: {php: 5.3.9}`` in the composer.json, as done in the Symfony demo. We should remove it in the installer though, to avoid forcing all Symfony projects to resolve deps in a 5.3-compatible way later (as we hope that most projects are not deployed on 5.3 anymore)

Removing the lock file will not help much: the installer is downloading an archive with vendors included, so the deps resolution still does not happen on the PHP version of the user.

**Comment by Tobion** [comment]
@stof 
> We can use config: {php: 5.3.9}

> But that could in theory also fail for people that use a newer PHP version. E.g. there could be a library that releases different versions for PHP 5.x and PHP 7.

**Comment by stof** [comment]
@Tobion the only solution for that would be to provide multiple downloads for the SE and then choosing the right one in the installer. Too complex IMO.

**Comment by Tobion** [comment]
The installer must not include the vendors in the archieve. Or it must only include the vendors that we can control and can ensure it works undependly of which PHP version like symfony/symfony.

**Comment by javiereguiluz** [comment]
@Tobion the installer has to include the vendors. That's what it makes it blazing fast.

**Comment by Pierstoval** [comment]
It could be better to check what are the real "changes" made by different versions of PHP when installing the vendors.
 
Making a comparison of the different `composer.lock` generated under different PHP versions can be a good start.
And then, if it's not "too big", we may, for example, include *all* dependencies in the vendors that are compatible with each version, even if some will be unused by other versions.

**Comment by stof** [comment]
@Pierstoval you cannot install multiple versions of the same package at the same time

**Comment by Pierstoval** [comment]
That's not what I'm talking about, it's more something like
`if PHP_VERSION < 5.4 then install ICU ; if PHP_VERSION > 5.6 then install another_package`
etc.
 
As I said:
> Making a comparison of the different `composer.lock` generated under different PHP versions can be a good start.

**Comment by stof** [comment]
@Pierstoval the issue here is that the composer.lock file should lock Doctrine 2.4 for PHP 5.3 compatible branches, not Doctrine 2.5 (which requires PHP 5.4+)

**Comment by WouterJ** [comment]
Related: https://github.com/symfony/symfony/issues/17056

**Comment by stof** [comment]
@WouterJ not sure. the user seems to have a corrupted lock file (maybe a lock file updated manually in a wrong way)

**Comment by Pierstoval** [comment]
Then the deploy script should be run on an environment with PHP 5.3 so the lock file is correct for anyone, and therefore the orm requirement should be changed from `^2.5` to `^2.4` for users to be able to run a `composer update` in their own environment.

**Comment by stof** [comment]
@Pierstoval the 2.8 branch has ``^2.4.8`` as constraint

**Comment by Pierstoval** [comment]
Oh, yeah, right, I don't know where I saw `^2.5`, but you're right.
The rest of my comment still seems pertinent to me :)

**Comment by javiereguiluz** [comment]
This is causing issues for some users (e.g. [this StackOverflow question](http://stackoverflow.com/questions/34592299/symfony-2-8-1-error-after-installation)).

In theory Symfony 2.8 works with PHP 5.3.9. In practice, Symfony 2.8 requires PHP 5.5+ because of Doctrine.

**Comment by Pierstoval** [comment]
@javiereguiluz At work I'm developing an app on Symfony 2.8 with PHP 5.4.45 and it works perfectly :confused:

**Comment by Pierstoval** [comment]
Actually I think that SensioLab need to update its build script or environment in order to install the vendors with PHP 5.3 as expected by everyone for compatibility reasons. And for Symfony3, build it with PHP 5.5.
I know it's quite cumbersome but actually it can be done by changing the [composer `config.platform` parameter](https://getcomposer.org/doc/06-config.md#platform). Maybe think about something similar on runtime?

**Comment by javiereguiluz** [comment]
@Pierstoval if you open for instance `Doctrine\Common\Proxy\ProxyGenerator`, you'll find this code incompatible with PHP 5.4 in line 61:

```php
    protected $placeholders = [
        'baseProxyInterface'   => Proxy::class,
        'additionalProperties' => '',
    ];
```

**Comment by Pierstoval** [comment]
@javiereguiluz I know, but if you run `composer update` with PHP 5.4 or if you specify the `config.platform` with `php: "5.4.45"`, this version of `doctrine/common` won't be installed. That's why I think the build script from SensioLab must be run with PHP 5.3 to avoid *any* incompatibility. Promise is made over PHP 5.3, so IMO it should be built with 5.3.

**Comment by COil** [comment]
I confirm that using:

    "config": {
        "platform": {
            "php": "5.4"
        },
        "bin-dir": "bin"
    },

Solved the problem too (I am also using 5.4.45 on Debian)

**Comment by fabpot** [comment]
I think adding PHP 5.3 as the platform configuration in the standard edition is the way to go. If someone has a newer version, he just has to update the default composer.json. That should fix almost all problems.

**Comment by Pierstoval** [comment]
@fabpot: I think you're right, I've been thinking about a solution for Composer, but there's nothing possible right now. What would be good is for Composer to allow some options to be overridable (like `extras`, `scripts`, `config` or even `autoload`).

**Comment by fabpot** [comment]
Done in d0e9308e807aae02c332897d610ad5eb49d81c1e

**Comment by Tobion** [comment]
This does not fix the issue fully as I explained initially. There can still be libraries that are for example compatible with PHP 5.3 but not with PHP 7 (e.g. phpunit). So the lock would install stuff that won't work for some users. The only solution is to remove the lock file.

**Comment by Tobion** [comment]
And even worse people must remember to update this part of the composer.json from SE every time. Otherwise it will cause hard to find bugs when they add a dependency but it doesn't actually work in their environment.

**Comment by Pierstoval** [comment]
@tobion There's a discussion about bringing this user-logic into the installer here: symfony/symfony-installer#234

**Comment by andig** [comment]
> So if we lock in the one for 5.3.9, a user coming with PHP 7 might not be able to run symfony as well.
  
> This does not fix the issue fully as I explained initially. There can still be libraries that are for example compatible with PHP 5.3 but not with PHP 7 (e.g. phpunit).

That is what's happening in https://github.com/symfony/symfony-demo/issues/343 when installing additional packages, only the other way round.

The use of config.platform.php in addition to `require: php>=5.3.9` prevents the packages (which only exist for php >5.5) from being installed unless composer.json is required due to https://github.com/symfony/symfony-standard/commit/d0e9308e807aae02c332897d610ad5eb49d81c1e.

**Comment by ChadSikorra** [comment]
This causes some very confusing issues when installing a new project via composer rather than than the Symfony installer. It should probably at least be noted in [the docs](http://symfony.com/doc/current/setup.html#creating-symfony-applications-with-composer).
